apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-expressapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Amith-B/kubernetes-argocd'
    path: app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-express-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
