apiVersion: v1
kind: Service
metadata:
  name: my-expressapp-service
spec:
  selector:
    app: my-expressapp
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: LoadBalancer
